[project]
name = 'Elevator-Floor-Button-Press-Redundancy-Optimizer'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.button-press-confidence-erosion-algorithm]
path = 'contracts/button-press-confidence-erosion-algorithm.clar'
clarity_version = 3
epoch = '3.2'

[contracts.emergency-button-accessibility-inverse-correlation-maximizer]
path = 'contracts/emergency-button-accessibility-inverse-correlation-maximizer.clar'
clarity_version = 3
epoch = 'latest'

[contracts.floor-arrival-timing-expectation-manipulation-service]
path = 'contracts/floor-arrival-timing-expectation-manipulation-service.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
